name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: Set up Node.js
        uses: actions/setup-node@8f9cc178b6e843639351e0bd5d638e5fd0a8dec7
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run compile
